// <auto-generated />
using System;
using ManLearning.Infrastructure.Persistence.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManLearning.Infrastructure.Persistence.EfCore.Migrations
{
    [DbContext(typeof(ManLearningDbContext))]
    [Migration("20261003013802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManLearning.Domain.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("ManLearning.Domain.Courses.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Position")
                        .IsUnique();

                    b.ToTable("Lessons", (string)null);
                });

            modelBuilder.Entity("ManLearning.Domain.Learners.Streak", b =>
                {
                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentLength")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LastActiveDate")
                        .HasColumnType("date");

                    b.Property<int>("LongestLength")
                        .HasColumnType("int");

                    b.HasKey("LearnerId");

                    b.ToTable("Streaks", (string)null);
                });

            modelBuilder.Entity("ManLearning.Domain.Progress.LessonProgress", b =>
                {
                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LearnerId", "LessonId");

                    b.ToTable("LessonProgress", (string)null);
                });

            modelBuilder.Entity("ManLearning.Domain.Xp.XpAward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AwardedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.ToTable("XpAwards", (string)null);
                });

            modelBuilder.Entity("ManLearning.Domain.Courses.Lesson", b =>
                {
                    b.HasOne("ManLearning.Domain.Courses.Course", null)
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ManLearning.Domain.Quizzes.Quiz", "Quiz", b1 =>
                        {
                            b1.Property<Guid>("LessonId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("LessonId");

                            b1.ToTable("Quizzes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LessonId");

                            b1.OwnsMany("ManLearning.Domain.Quizzes.Question", "Questions", b2 =>
                                {
                                    b2.Property<Guid>("LessonId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("nvarchar(1000)");

                                    b2.HasKey("LessonId", "Id");

                                    b2.ToTable("Questions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("LessonId");

                                    b2.OwnsMany("ManLearning.Domain.Quizzes.AnswerChoice", "AnswerChoices", b3 =>
                                        {
                                            b3.Property<Guid>("LessonId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<Guid>("QuestionId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<Guid>("Id")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<bool>("IsCorrect")
                                                .HasColumnType("bit");

                                            b3.Property<string>("Text")
                                                .IsRequired()
                                                .HasMaxLength(500)
                                                .HasColumnType("nvarchar(500)");

                                            b3.HasKey("LessonId", "QuestionId", "Id");

                                            b3.ToTable("AnswerChoices", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("LessonId", "QuestionId");
                                        });

                                    b2.Navigation("AnswerChoices");
                                });

                            b1.Navigation("Questions");
                        });

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("ManLearning.Domain.Courses.Course", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
