// <auto-generated />
using System;
using ManLearning.Infrastructure.Persistence.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManLearning.Infrastructure.Persistence.EfCore.Migrations
{
    [DbContext(typeof(ManLearningDbContext))]
    partial class ManLearningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ManLearning.Domain.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("ManLearning.Domain.Courses.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Position")
                        .IsUnique();

                    b.ToTable("Lessons", (string)null);
                });

            modelBuilder.Entity("ManLearning.Domain.Learners.Streak", b =>
                {
                    b.Property<Guid>("LearnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentLength")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LastActiveDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LongestLength")
                        .HasColumnType("INTEGER");

                    b.HasKey("LearnerId");

                    b.ToTable("Streaks", (string)null);
                });

            modelBuilder.Entity("ManLearning.Domain.Progress.LessonProgress", b =>
                {
                    b.Property<Guid>("LearnerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("LearnerId", "LessonId");

                    b.ToTable("LessonProgress", (string)null);
                });

            modelBuilder.Entity("ManLearning.Domain.Xp.XpAward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AwardedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.ToTable("XpAwards", (string)null);
                });

            modelBuilder.Entity("ManLearning.Domain.Courses.Lesson", b =>
                {
                    b.HasOne("ManLearning.Domain.Courses.Course", null)
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ManLearning.Domain.Quizzes.Quiz", "Quiz", b1 =>
                        {
                            b1.Property<Guid>("LessonId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.HasKey("LessonId");

                            b1.ToTable("Quizzes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LessonId");

                            b1.OwnsMany("ManLearning.Domain.Quizzes.Question", "Questions", b2 =>
                                {
                                    b2.Property<Guid>("LessonId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("LessonId", "Id");

                                    b2.ToTable("Questions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("LessonId");

                                    b2.OwnsMany("ManLearning.Domain.Quizzes.AnswerChoice", "AnswerChoices", b3 =>
                                        {
                                            b3.Property<Guid>("LessonId")
                                                .HasColumnType("TEXT");

                                            b3.Property<Guid>("QuestionId")
                                                .HasColumnType("TEXT");

                                            b3.Property<Guid>("Id")
                                                .HasColumnType("TEXT");

                                            b3.Property<bool>("IsCorrect")
                                                .HasColumnType("INTEGER");

                                            b3.Property<string>("Text")
                                                .IsRequired()
                                                .HasMaxLength(500)
                                                .HasColumnType("TEXT");

                                            b3.HasKey("LessonId", "QuestionId", "Id");

                                            b3.ToTable("AnswerChoices", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("LessonId", "QuestionId");
                                        });

                                    b2.Navigation("AnswerChoices");
                                });

                            b1.Navigation("Questions");
                        });

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("ManLearning.Domain.Courses.Course", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
