using ManLearning.Domain.Xp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ManLearning.Infrastructure.Persistence.EfCore.Configurations;

/// <summary>
/// Maps <see cref="XpAward"/> as an append-only log. There is no natural key (a learner can earn
/// multiple awards with the same reason/timestamp in theory), so a shadow <c>Id</c> primary key
/// is generated by the database rather than invented in Domain.
/// </summary>
internal sealed class XpAwardConfiguration : IEntityTypeConfiguration<XpAward>
{
    public void Configure(EntityTypeBuilder<XpAward> award)
    {
        award.ToTable("XpAwards");
        award.Property<Guid>("Id").ValueGeneratedOnAdd();
        award.HasKey("Id");
        award.Property(a => a.LearnerId).HasConversion(IdValueConverters.LearnerId);
        award.Property(a => a.Amount).IsRequired();
        award.Property(a => a.Reason).IsRequired().HasMaxLength(500);
        award.Property(a => a.AwardedAtUtc).IsRequired();
        award.HasIndex(a => a.LearnerId);
    }
}
